//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int ID { get; set; }
        public string LaptopName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> FactoryID { get; set; }
    
        public virtual Factory Factory { get; set; }
    }
}
